POST http://localhost:8080/api/v1/users
Content-Type: application/json

{
  "name": "Rian Ihsan",
  "occupation": "Backend",
  "email": "example@gmail.com",
  "password": "RianTest123"
}

###
POST http://localhost:8080/api/v1/verify
Content-Type: application/json

{
  "email": "example@gmail.com",
  "otp": "164637"
}


###
POST http://localhost:8080/api/v1/sessions
Content-Type: application/json

{
  "email": "example@gmail.com",
  "password": "RianTest123"
}