// Code generated by mockery v2.36.0. DO NOT EDIT.

package mocks

import (
	user "github.com/RianIhsan/raise-unity/user"
	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// FindValidOTP provides a mock function with given fields: userID, otp
func (_m *Service) FindValidOTP(userID int, otp string) (user.OTP, error) {
	ret := _m.Called(userID, otp)

	var r0 user.OTP
	var r1 error
	if rf, ok := ret.Get(0).(func(int, string) (user.OTP, error)); ok {
		return rf(userID, otp)
	}
	if rf, ok := ret.Get(0).(func(int, string) user.OTP); ok {
		r0 = rf(userID, otp)
	} else {
		r0 = ret.Get(0).(user.OTP)
	}

	if rf, ok := ret.Get(1).(func(int, string) error); ok {
		r1 = rf(userID, otp)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserByEmail provides a mock function with given fields: email
func (_m *Service) GetUserByEmail(email string) (user.User, error) {
	ret := _m.Called(email)

	var r0 user.User
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (user.User, error)); ok {
		return rf(email)
	}
	if rf, ok := ret.Get(0).(func(string) user.User); ok {
		r0 = rf(email)
	} else {
		r0 = ret.Get(0).(user.User)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserByID provides a mock function with given fields: ID
func (_m *Service) GetUserByID(ID int) (user.User, error) {
	ret := _m.Called(ID)

	var r0 user.User
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (user.User, error)); ok {
		return rf(ID)
	}
	if rf, ok := ret.Get(0).(func(int) user.User); ok {
		r0 = rf(ID)
	} else {
		r0 = ret.Get(0).(user.User)
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Login provides a mock function with given fields: input
func (_m *Service) Login(input user.LoginInput) (user.User, error) {
	ret := _m.Called(input)

	var r0 user.User
	var r1 error
	if rf, ok := ret.Get(0).(func(user.LoginInput) (user.User, error)); ok {
		return rf(input)
	}
	if rf, ok := ret.Get(0).(func(user.LoginInput) user.User); ok {
		r0 = rf(input)
	} else {
		r0 = ret.Get(0).(user.User)
	}

	if rf, ok := ret.Get(1).(func(user.LoginInput) error); ok {
		r1 = rf(input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RegisterUser provides a mock function with given fields: input
func (_m *Service) RegisterUser(input user.RegisterUserInput) (user.User, error) {
	ret := _m.Called(input)

	var r0 user.User
	var r1 error
	if rf, ok := ret.Get(0).(func(user.RegisterUserInput) (user.User, error)); ok {
		return rf(input)
	}
	if rf, ok := ret.Get(0).(func(user.RegisterUserInput) user.User); ok {
		r0 = rf(input)
	} else {
		r0 = ret.Get(0).(user.User)
	}

	if rf, ok := ret.Get(1).(func(user.RegisterUserInput) error); ok {
		r1 = rf(input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ResendOTP provides a mock function with given fields: email
func (_m *Service) ResendOTP(email string) (user.OTP, error) {
	ret := _m.Called(email)

	var r0 user.OTP
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (user.OTP, error)); ok {
		return rf(email)
	}
	if rf, ok := ret.Get(0).(func(string) user.OTP); ok {
		r0 = rf(email)
	} else {
		r0 = ret.Get(0).(user.OTP)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SaveAvatar provides a mock function with given fields: userID, file
func (_m *Service) SaveAvatar(userID int, file string) (user.User, error) {
	ret := _m.Called(userID, file)

	var r0 user.User
	var r1 error
	if rf, ok := ret.Get(0).(func(int, string) (user.User, error)); ok {
		return rf(userID, file)
	}
	if rf, ok := ret.Get(0).(func(int, string) user.User); ok {
		r0 = rf(userID, file)
	} else {
		r0 = ret.Get(0).(user.User)
	}

	if rf, ok := ret.Get(1).(func(int, string) error); ok {
		r1 = rf(userID, file)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateUser provides a mock function with given fields: _a0
func (_m *Service) UpdateUser(_a0 user.User) (user.User, error) {
	ret := _m.Called(_a0)

	var r0 user.User
	var r1 error
	if rf, ok := ret.Get(0).(func(user.User) (user.User, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(user.User) user.User); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(user.User)
	}

	if rf, ok := ret.Get(1).(func(user.User) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// VerifyEmail provides a mock function with given fields: email, otp
func (_m *Service) VerifyEmail(email string, otp string) error {
	ret := _m.Called(email, otp)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(email, otp)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
