name: Docker Image CI

on:
  push:
    branches: "develop"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/yondev:latest
      -
        name: connect ssh
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            sudo docker stop ${{ secrets.CNAME }}
            sudo docker rm ${{ secrets.CNAME }}
            sudo docker rmi ${{ secrets.DOCKERHUB_USERNAME }}/yondev
            sudo docker run --name ${{ secrets.CNAME }} -p 8080:8080 -d \
            -e DB_HOST=${{ secrets.DB_HOST }} \
            -e DB_PORT=${{ secrets.DB_PORT }} \
            -e DB_USER=${{ secrets.DB_USER }} \
            -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
            -e DB_NAME=${{ secrets.DB_NAME }} \
            -e SECRET_KEY=${{ secrets.SECRET_KEY }} \
            -e CLOUDINARY_URL=${{ secrets.CLOUDINARY_URL }} \
            -e SMTP_PASS=${{ secrets.SMTP_PASS }} \
            -e SMTP_USER=${{ secrets.SMTP_USER }} \
            -e SMTP_PORT=${{ secrets.SMTP_PORT }} \
            -e MSERVER=${{ secrets.MSERVER }} \
            -e MCLIENT=${{ secrets.MCLIENT }} \
            ${{ secrets.DOCKERHUB_USERNAME }}/yondev
